package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.net.URLStreamHandler;

@Controller // this class is a controller
@RequestMapping(path="/demo") // URLs start with /demo (after application path)
public class MainController {
  @Autowired // get the bean called userRepository, which is auto-generated by Spring. user it ot handle data
  private UserRepository userRepository;

  @PostMapping(path="/add") // map only post requests
  public @ResponseBody String addNewUser(@RequestParam String name, @RequestParam String email) {
    // @ResponseBody means the returned string is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    User n = new User();
    n.setName(name);
    n.setEmail(email);
    userRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<User> getAllUsers() {
    // this returns a JSON or XML with the users
    return userRepository.findAll();
  }
}
